#!/bin/bash

# DubVim - modeline, notes, info, ... {
# vim: set sw=4 ts=4 sts=4 et tw=78 foldmarker={,} foldlevel=0 foldmethod=marker spell:
#
#
#                     _____         _   _    _ _
#                    (____ \       | | | |  | (_)
#                     _   \ \ _   _| | | |  | |_ ____
#                    | |   | | | | | || \ \/ /| |    \
#                    | |__/ /| |_| | |_) )  / | | | | |
#                    |_____/  \____|____/ \/  |_|_|_|_|
#
#               Per Juchtmans <dubgeiser+vimconfig@gmail.com>
#
#   DubVim installer
#   This installer assumes that you have cloned in $VIMDIR
#
#
# }

VIMDIR=~/.vim

pushd
cd ~
ln -s $VIMDIR/vimrc .vimrc
cd $VIMDIR
mkdir -p tmp
git submodule update --init
vim -u NONE -c "helptags ALL" -c q
popd
