#!/usr/bin/env bash

# DubVim - modeline, notes, info, ... {
# vim: set sw=4 ts=4 sts=4 et tw=78 foldmarker={,} foldlevel=0 foldmethod=marker spell:
#
#
#                     _____         _   _    _ _
#                    (____ \       | | | |  | (_)
#                     _   \ \ _   _| | | |  | |_ ____
#                    | |   | | | | | || \ \/ /| |    \
#                    | |__/ /| |_| | |_) )  / | | | | |
#                    |_____/  \____|____/ \/  |_|_|_|_|
#
#               Per Juchtmans <dubgeiser+vimconfig@gmail.com>
#
#   DubVim installer
#   This installer assumes that you have cloned in $VIMDIR
#
#
# }

echo
echo '---> Updating local install'
git pull --ff-only

echo
echo '---> Updating submodules'
git submodule update --remote --merge

echo
echo '---> Checking for extra update steps'
updated_submodules=$(git status --short | egrep 'pack\/' | sed 's/ M //' | cut -d/ -f4)
if [[ "$updated_submodules" != "" ]]; then
    for each in $updated_submodules; do
        printf "\t - checking %s\n" "$each"
        if [[ "$each" == "phpactor" ]]; then
            echo '---> Updating PHPActor'
            vim -c "call phpactor#Update()" -c q
        fi
    done
    echo
    echo '---> Updating help'
    vim -c "helptags ALL" -c q
else
    echo 'No extra update steps necessary'
fi
