#!/usr/bin/env bash

# DubVim - modeline, notes, info, ... {
# vim: set sw=4 ts=4 sts=4 et tw=78 foldmarker={,} foldlevel=0 foldmethod=marker spell:
#
#
#                     _____         _   _    _ _
#                    (____ \       | | | |  | (_)
#                     _   \ \ _   _| | | |  | |_ ____
#                    | |   | | | | | || \ \/ /| |    \
#                    | |__/ /| |_| | |_) )  / | | | | |
#                    |_____/  \____|____/ \/  |_|_|_|_|
#
#               Per Juchtmans <dubgeiser+vimconfig@gmail.com>
#
#   DubVim installer
#   This installer assumes that you have cloned in $VIMDIR
#
#
# }

git pull --ff-only
git submodule update --remote --merge
vim -c "call phpactor#Update()" -c "helptags ALL" -c q
